### ISSUE TITLE
subscribeResponse null when using 

### ISSUE THREAD

**Issue by Envaya** [aelvan/mailchimp-subscribe-craft#119]
After a user has signed up for our newsletter successfully, I want to reload the page and jump to the success message above the form:
{{ redirectInput('ueber-uns/newsletter#message') }}

however, when I use redirectInput, the subscribeResponse seems to be null.

**Comment by mmikkel** [comment]
Yeah, that's because the subscribe response is set as a route param via Craft's [UrlManager class](https://docs.craftcms.com/api/v3/craft-web-urlmanager.html#public-methods). Those don't survive a redirect. But, the redirect only happens for successful requests, so in most cases you don't need the response... if the user is redirected, you already know the subscribe/unsubscribe action was successful.

A workaround if you do need the response for successful requests is to remove the redirect input, and do a `{% redirect siteUrl('ueber-uns/newsletter#message') %}` in Twig if the response is successful.
