### ISSUE TITLE
Missing a dependency

### ISSUE THREAD

**Issue by dralshehri** [aelvan/mailchimp-subscribe-craft#20]
Installed v1.0.0 and tried to subscribe using the example template but I got an error of "Mailchimp\Mailchip class was not found"

Perhaps the "pacely/mailchimp-apiv3" package needs to be installed through composer.

**Comment by aelvan** [comment]
Yeah, sorry, the library hadn't been checked into git, fixed it now . Try downloading it and see if it works better now.

**Comment by dralshehri** [comment]
It works! but I noticed other 2 issues:

1. when the fields mcvars[FNAME] and mcvars[LNAME] are not submitted with the form like in case of using an email field only, I get the following error and I had to include those fields as hidden empty field to make it work:
    ```
    PHP Error [500]
    Undefined property: Exception::$status     (/home/vagrant/site/craft/plugins/mailchimpsubscribe/services/MailchimpSubscribeService.php:72)
    ```

2. I use an ajax form to subscribe, and the response shows errorCode of 200 and success value of true for both cases of successful subscription and already subscribed messages.
What I expect is that "Already subscribed" should be considered as an error with false success value, and "Subscribed successfully" should be considered as a success with true success value, and no errorCode. That way it would be easier to know the type of response.

**Comment by aelvan** [comment]
1) Can you try again, there was a bug where mailchimp would return an error if the merge_vars variable was posted but empty. Should be fixed in the latest commit.

2) Yes, I spent some time thinking about that... It is the way it is now to maintain backwards compability. The variable named "errorCode" should have been "code", that's just unfortunate naming. And in the last version of the API i used, mailchimp didn't return different responses if the email already were subscribed or not, so the plugin returned success and code 200. If I were to change any of this, existing code would break. 

But, I agree that it's a bit weird. I'm contemplating maybe adding a config variable for setting the code/status to be returned if already subscribed, but it doesn't feel optimal either.

But, if you could also use the string returned to check if the user had already subscribed or not, although a bit fragile. Or, if you use ajax, you could run the checkIfSubscribed action before actually subscribing.

**Comment by dralshehri** [comment]
1) Solved. Thanks!

2) I think the subscribe method will check if email is already subscribed, so why I would check two times? I suggest changing the success value on line 58 to false, that way if we're subscribing an email and it's been already subscribed we should show success:false to reflect the success of subscribe method not the checking itself. Will it break anything if I do so?
