### ISSUE TITLE
Trying to get property 'status' of non-object

### ISSUE THREAD

**Issue by bhashkar007** [aelvan/mailchimp-subscribe-craft#81]
I am getting this strange error while everything working perfectly before. Please see screenshot.
![2019-06-11-10-54-www](https://user-images.githubusercontent.com/1473647/59246456-0e743780-8c3a-11e9-88ea-c85c3e8156ab.png)

Is it because of PHP v7.2.17?

**Comment by aelvan** [comment]
There is probably an underlying error that triggers the catch, the error message is just an error in the error handling (duh). This has been fixed in 3.0.0. If you haven't resolved it already, try upgrading (read the release notes/changelog, alot of stuff has changed), and check your logs/debug bar for the actual error message.
